name: Pull request CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  buildAndTest:
    runs-on: macos-latest
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Run unit tests
        run: ./gradlew test
      - name: Archive production artifacts
        uses: actions/upload-artifact@v3.1.1
        with:
          name: reports
          path: | 
            **/build/reports/
      - name: Archive APK
        uses: actions/upload-artifact@v3.1.1
        with:
          name: apk
          path: app/build/outputs/apk/

  checkDetekt:
    runs-on: macos-latest
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check detekt
        run: ./gradlew detekt
      - name: Upload detekt report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: detekt_report
          path: |
            **/build/reports/

  checkLint:
    runs-on: macos-latest
    steps:
      - name: Checkout the code to specific branch
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Check lint
        run: ./gradlew lint
      - name: Upload lint report
        uses: actions/upload-artifact@v3.1.1
        with:
          name: lint_report
          path: |
            **/build/reports/
    
